version: '3'
services:
  express-app:
    container_name: backend_express
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${EXPRESS_PORT}:${EXPRESS_PORT}'
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    depends_on:
      - mysql-db
    environment:
      - TZ=Asia/Seoul   # 호스트 시간대에 맞게 설정
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_HOST=mysql-db
  
  mysql-db:
    container_name: ${MYSQL_NAME}
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${EXTERNAL_MYSQL_PORT}:${MYSQL_PORT}"

volumes:
  express-app-volume:   # 볼륨 이름 설정