version: '3'
services:
  express-app:
    container_name: backend_express
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${EXPRESS_PORT}:${EXPRESS_PORT}'
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    depends_on:
      - mysql-db
    environment:
      TZ: "Asia/Seoul"
      MYSQL_PORT: "${MYSQL_PORT}"
      MYSQL_HOST: "${MYSQL_NAME}"
    links:
      - mysql-db
  
  mysql-db:
    container_name: ${MYSQL_NAME}
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${EXTERNAL_MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  express-app-volume:   # express 볼륨
  mysql-data: # mysql 볼륨